### ISSUE TITLE
verify data stored on local estuary setup

### ISSUE THREAD

**Issue by ProgramCpp** [application-research/estuary#113]
I need help verifying data stored on my local estuary setup. 

Steps:
- setup estuary
- setup shuttle
- setup estuary-web
- Add file via estuary endpoint

when verifying the cid, i get a message "This CID is not found. It might be pinned by a IPFS Node, you can use the dweb.link URL to check"

the content is accessible at the IPFS gateway,
https://bafkqactumvzxictumvzxicq.ipfs.dweb.link/

I would like to verify that estuary node is pinning the data and filecoin deals are made.

Thanks

**Comment by alvin-reyes** [comment]
@ProgramCpp you can try setting up your local and connect it to `estuary_calibnet` - this is the Test Network but it depends if there are storage providers who can accommodate the deal. 

The easiest would be to request access to the production estuary.tech and upload your data there. We have a few [scripts](https://github.com/application-research/estuary/blob/master/scripts/samples/batch-cid-add-ipfs.sh) that can help you upload and make a deal on the estuary.tech but it needs an invite code (the API Key) to run.

**Comment by ProgramCpp** [comment]
@alvin-reyes can you share instructions to connect calibnet? or, could you help with connecting estuary to local storage providers setup?

**Comment by en0ma** [comment]
@ProgramCpp  can you past the link you used in verifying the CID?

**Comment by ProgramCpp** [comment]
@en0ma Im checking the `/verify-cid` endpoint

**Comment by en0ma** [comment]
@ProgramCpp please share the full URL you are suing to verify, not just the path

**Comment by en0ma** [comment]
@ProgramCpp any word on this, so we can close this out

**Comment by ProgramCpp** [comment]
@en0ma the url is `http://localhost:4444/verify-cid`

i could not setup my local instance. I've got an invite code to estuary production, that I'm using
