### ISSUE TITLE
authorization error for pinning API with local estuary setup 

### ISSUE THREAD

**Issue by ProgramCpp** [application-research/estuary#114]
i setup estuary locally and tried pinning a file i added with the below API, 
https://docs.estuary.tech/pinning-add

But i get authorization error, `{"error":{"reason":"ERR_INVALID_AUTH"}}`

please help.

**Comment by gmelodie** [comment]
Hey there! I assume you're running your own node (please let me know otherwise). If that's the case, when you setup estuary with `./estuary setup` for the first time you should get an API key like this: `EST9d708186-43cf-44ac-8206-a6cb1dbacdeaARY`. On your request, you have to add a header that contains that API key: `Authorization: Bearer EST9d708186-43cf-44ac-8206-a6cb1dbacdeaARY`

**Comment by ProgramCpp** [comment]
Hi @gmelodie, i followed the steps you mentioned. please see the output below. `content/add` API works fine but not `/pinning/pins`

```
> curl -X POST http://localhost:3004/content/add -H "Authorization: Bearer EST64eac9ad-8d07-410d-b64a-2b75f6cb33c2ARY" -H "Accept: application/json" -H "Content-Type: multipart/form-data" -F "data=@./test.file"
{"cid":"bafkqafdumvzxictumvzxictumvzxictumvzxicq","estuaryId":4,"providers":["/ip4/192.168.0.171/tcp/6744/p2p/12D3KooWC9b7XQmLngkNLV5Nf6aDvwTghHdQqpQ1BMH1jR6PFj3R","/ip4/127.0.0.1/tcp/6744/p2p/12D3KooWC9b7XQmLngkNLV5Nf6aDvwTghHdQqpQ1BMH1jR6PFj3R","/ip4/10.237.114.241/tcp/30182/p2p/12D3KooWC9b7XQmLngkNLV5Nf6aDvwTghHdQqpQ1BMH1jR6PFj3R","/ip4/124.123.83.151/tcp/30182/p2p/12D3KooWC9b7XQmLngkNLV5Nf6aDvwTghHdQqpQ1BMH1jR6PFj3R"]}
> curl -X POST http://localhost:3004/pinning/pins -d '{ "name": "test.file", "cid": "bafkqafdumvzxictumvzxictumvzxictumvzxicq" }' -H "Content-Type: application/json" -H "Authorization: Bearer  EST64eac9ad-8d07-410d-b64a-2b75f6cb33c2ARY"
{"error":{"reason":"ERR_INVALID_AUTH"}}
```

**Comment by gmelodie** [comment]
Interesting. I was able to reproduce the bug and although some issue is definitely happening, it's surely not an invalid API key issue. Do you want to try and figure out what's going on and submit a PR? Also, if you added content through `content/add` you should not need to manually pin it with `pinning/pins`, it should already be pinned (you can check that by [listing pins](https://docs.estuary.tech/pinning-list).

**Comment by alvin-reyes** [comment]
Just tried this. The issue is that you have an additional space between `Bearer` and the `token`

```
curl -X POST http://localhost:3004/pinning/pins -d '{ "name": "test.file", "cid": "bafkqafdumvzxictumvzxictumvzxictumvzxicq" }' -H "Content-Type: application/json" -H "Authorization: Bearer  EST64eac9ad-8d07-410d-b64a-2b75f6cb33c2ARY"
```

```
curl -X POST http://localhost:3004/pinning/pins -d '{ "name": "test.file", "cid": "bafkqafdumvzxictumvzxictumvzxictumvzxicq" }' -H "Content-Type: application/json" -H "Authorization: Bearer EST64eac9ad-8d07-410d-b64a-2b75f6cb33c2ARY"
```

![image](https://user-images.githubusercontent.com/4479171/157518726-d47b0256-2c6e-4975-8d34-d0234182418a.png)

I tested on my local with the same command (created the file and new API key)
```
curl -X POST http://localhost:3004/pinning/pins -d '{ "name": "test.file", "cid": "bafkqafdumvzxictumvzxictumvzxictumvzxicq" }' -H "Content-Type: application/json" -H "Authorization: Bearer EST23d2a6bd-053b-47a3-89a6-253af2b1217aARY" 
{"requestid":"1","status":"queued","created":"2022-03-09T19:34:20.366830588Z","pin":{"cid":"bafkqafdumvzxictumvzxictumvzxictumvzxicq","name":"test.file","origins":null,"meta":null},"delegates":["/ip4/172.18.0.2/tcp/6744/p2p/12D3KooWG43GNUDSrB7UfftrjoJsoMKEJSN8vFQEoEh9ebRSerSw","/ip4/127.0.0.1/tcp/6744/p2p/12D3KooWG43GNUDSrB7UfftrjoJsoMKEJSN8vFQEoEh9ebRSerSw"],"info":null}
```

**Comment by ProgramCpp** [comment]
oh yes! it worked. Thanks for your help 👍 
closing the bug.
