### ISSUE TITLE
Deal status changed from "active" to "deal on chain"

### ISSUE THREAD

**Issue by tubleronchik** [application-research/estuary#132]
I saved some data to Filecoin using Estuary. On 18th of march I saw that my data was backed up to the Filecoin Network. 
![image](https://user-images.githubusercontent.com/36592446/159541009-5db8c0be-cac8-4765-8eb4-71acbcc86ab4.png)
Few days later I coul see that my deals are again on chain for the same file.
![image](https://user-images.githubusercontent.com/36592446/159541160-fddfa193-a99c-467a-bd20-dfbe03ddc474.png)

**Comment by en0ma** [comment]
@tubleronchik can you check the `deals/debug` page and look for possible error messages for those providers? this looks like the deals were slashed, if they were, it should show up on the debug page

**Comment by tubleronchik** [comment]
> @tubleronchik can you check the `deals/debug` page and look for possible error messages for those providers? this looks like the deals were slashed, if they were, it should show up on the debug page

Hi. Here is my logs: 
![image](https://user-images.githubusercontent.com/36592446/165927014-078e0b25-4224-4ffb-b42a-457998ac4e2e.png)

I couldn't find logs for local id `23674129` on the debug page.

**Comment by en0ma** [comment]
Hi @tubleronchik, this page shows recent debug messages, so it is likely you won't see it, but it should be there. It is likely a case of a slashed deal. I think we will have to work on a page to track slashed deals per user.

Anyways, I will be closing this for now, please feel free to comment when this happens again.
