### ISSUE TITLE
Many Estuary deals stuck on "StorageDealWaitingForData" 

### ISSUE THREAD

**Issue by brendalee** [application-research/estuary#143]
SP feedback: 

Stephane: It seems to be for the larger deals (32GiB) as the smaller ones (4GiB, 8GiB, 16GiB) are coming through without too much problems.
I'm also having some transfer trouble. At this stage, I have about 70% failure rate with a combination of both problems above (last 50 deals, 16 were successful).

Stuberman: 
Logs from last 100 Estuary deals which did not error out (many stuck in StorageDealWaitingForData)
[Estuary 2022.txt](https://github.com/application-research/estuary/files/8392325/Estuary.2022.txt)

Slack thread with more details: https://filecoinproject.slack.com/archives/C02GQUMFQVA/p1646316105412969

**Comment by brendalee** [comment]
@en0ma any update that we could share on this? :) thanks for the investigations that you've done!

**Comment by en0ma** [comment]
@brendalee sorry about the delay in getting back to you on this. Actually, it is tricky to completely tell if the resource manager changes @whyrusleeping deployed is helping (maybe @whyrusleeping can speak to that, as I am still learning the ropes in this area). Looking at the Grafana dashboard at https://protocollabs.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-protocollabs-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bjob%3D%5C%22shuttle%5C%22%7D%20%7C~%20%5C%22rcmgr%5C%22%22%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D, I can still see some resource limit exceeded warnings.

I am not sure how to go from here, maybe you, @whyrusleeping, and I can get on a call and think of a way forward.

**Comment by brendalee** [comment]
thanks @en0ma ! will close this issue for now until we hear SPs talk about it again :)
