### ISSUE TITLE
Listing pins is still too slow

### ISSUE THREAD

**Issue by elijaharita** [application-research/estuary#16]
Apparently timing out even with low limit query param set (1), so probably still has to do with the database. Integrating pin statuses into the database sounds really good, but still need to look into the technical challenges of that. It does seem doable to me, though.

**Comment by elijaharita** [comment]
Update - changes applied by Why on the master branch allow running the filters as part of the database query under certain conditions!

**Comment by marshall** [comment]
@elijaharita sounds like this got mostly resolved back in July, just want to follow up to see if we can close this out

**Comment by elijaharita** [comment]
I haven't been tracking this, fine to close
