### ISSUE TITLE
Add support for custom metadata on pins

### ISSUE THREAD

**Issue by gmelodie** [application-research/estuary#163]
As per requested by @3456091 on #157 and ecouraged by [the IPFS docs](https://ipfs.github.io/pinning-services-api-spec/#section/Custom-metadata/Pin-metadata), we should support users submitting custom metadata on `handleAddPin` (maybe on other parts of the code as well? need to check).

**Comment by jimmylee** [comment]
https://ipfs.github.io/pinning-services-api-spec/#tag/pins/paths/~1pins/post

**Comment by gmelodie** [comment]
#157 shows it's not

**Comment by gmelodie** [comment]
Nvm, this was fixed on https://github.com/application-research/estuary/pull/160
