### ISSUE TITLE
Merge /collections/content/:collection_id and /collections/fs/list endpoints

### ISSUE THREAD

**Issue by gmelodie** [application-research/estuary#164]
As an effort to make the estuary API more clean and obvious, we could merge these two endpoints. They essentially do the same thing: list contents of a collection. The difference is in which information each shows. `/collections/fs/list` shows information about collection paths and subdirectories, whereas `/collections/content/:collection_id` has stats about pins and whatnot. I think that these two could be one endpoint with optional arguments to show directory structure or stats.

**Comment by gmelodie** [comment]
@en0ma what do you think about this one?

**Comment by en0ma** [comment]
> @en0ma what do you think about this one?

I will find time to have a look first thing tomorrow morning, I will update you on it.

**Comment by en0ma** [comment]
I agree @gmelodie we should merge them under `/collections/:collection_id/content`
