### ISSUE TITLE
/collections/fs/list occassionally returns null for previously uploaded path 

### ISSUE THREAD

**Issue by 3456091** [application-research/estuary#168]
I'm still investigating the specifics, but the gist is that if I run :

`curl -XPOST -H "Authorization: Bearer $AUTH_TOK" "https://upload.estuary.tech/content/add?collection=$COL&collectionPath=/$(basename $f)" -F data=@"$f"`

Then:

`curl  -H "Authorization: Bearer $AUTH_TOK" "https://api.estuary.tech/collections/fs/list?col=$COL&dir=/$(basename "$f")"`

I normally receive something like this back from the latter:

`[{"name":"19971205.gif","type":"file","size":37412,"contId":28528783,"cid":"$CID"}]`

However, every so often I receive `null` instead. This is definitely intermittent, but once it's happened it seems to persist.

**Comment by gmelodie** [comment]
This is interesting... Could you:
1. Fire up a local estuary node with `./estuary --logging 2>&1`
2. Try to reproduce the issue
3. Post the estuary logs that the node outputs here?

**Comment by corinne-antonia** [comment]
Hey @3456091, did you see @gmelodie response? If so, does this solve it for you? Can I close this?

**Comment by 3456091** [comment]
Well, the original symptom only occurred sporadically, so I can't judge whether the fix works. 🙂 No objections to closing, though.
