### ISSUE TITLE
CICD actions for automated Estuary builds

### ISSUE THREAD

**Issue by jlogelin** [application-research/estuary#172]
As a developer, I want to have automated master gates to perform the following tasks:

- automated binary builds
- execution/validation of unit tests
- static code analysis / linting
- a framework for easily cutting releases

**Comment by brendalee** [comment]
wahoo! @jlogelin would be great if you can help lead this :D

**Comment by jlogelin** [comment]
WIP fork here: https://github.com/jlogelin/estuary for development purposes.

**Comment by jlogelin** [comment]
Completed the baseline of automated builds, units tests (they were already there) and release cutting framework.
