### ISSUE TITLE
Current filecoin-ffi submodule version fails to build on linux-arm machines

### ISSUE THREAD

**Issue by lanzafame** [application-research/estuary#176]
Commit version `5d00bb4` of filecoin-ffi does not build on linux arm. 

Commit version `8b32252` builds fine but I can't get estuary to build whilst using this version. Help would be greatly appreciated.

**Comment by alvin-reyes** [comment]
Discussion on this: https://filecoinproject.slack.com/archives/C016APFREQK/p1651702025773469?thread_ts=1651625638.198569&cid=C016APFREQK

Conclusion, we need to use lotus v1.15.1 and ffi version 38f10cf6fa078b989fc774081cd65ba5c53636d8

I also added a PR to parameterize the specific commit hash we can use when we pull the filecoin-ffi submodule:
https://github.com/application-research/estuary/pull/179

**Comment by en0ma** [comment]
@alvin-reyes @lanzafame I will be closing this, for now, please feel free to reopen if you think this issue is not resolved.
