### ISSUE TITLE
Estuary API should not treat missing token as an error

### ISSUE THREAD

**Issue by softwareplumber** [application-research/estuary#180]
When an API request requiring some level of authorization is made, without a token, estuary treats this as an error and creates multiple log entries. 

This is a PITA because, for some reason, the web UI server generates such requests every second or so. The log traffic is pointless. Also the request causes a database search for a token with the value 'undefined', which is unnecessary.

This should be handled as a specific case, returning an unauthorized error to the API client without causing un-necessary database hits or log traffic.

**Comment by alvin-reyes** [comment]
I have prepared a PR for this @softwareplumber. Please check. I think its better if you just add your changes here.

https://github.com/application-research/estuary/tree/empty-auth-check

**Comment by alvin-reyes** [comment]
Resolved by https://github.com/application-research/estuary/pull/181
