### ISSUE TITLE
Check if we can connect to providers when pinning

### ISSUE THREAD

**Issue by gmelodie** [application-research/estuary#182]
When Estuary is pinning content [here](https://github.com/application-research/estuary/blob/eaefd9f7b0ac131b33572460a77aa5f500a2b092/pinning.go#L101-L105) tries to connect to the peers that provide the content to be pinned. We want to add a check on that piece of code to make sure at least one of the peers is reachable, otherwise we can fail early saying "unable to connect to any of the provider peers for the content to be pinned".

P.S.: careful when all the peers are aliases for the current node (it will try to dial itself). In that case even though none of the connect attempts work it doesn't matter because we won't have to connect to ourselves when effectively pinning.

**Comment by alvin-reyes** [comment]
Question: The piece of code here already checks if the host can connect to the list of peers. If it connects, it is reachable. If we loop through the peers here and one of them connects, then we can safely say that the specific peer is available. 

Do we want to check and just return an error if no peers is available? 

```
connectedToAtLeastOne := false
	for _, pi := range op.Peers {
		if err := s.Node.Host.Connect(ctx, pi); err != nil {
			log.Warnf("failed to connect to origin node for pinning operation: %s", err)
		} else {
			connectedToAtLeastOne = true
		}
	}

	if !connectedToAtLeastOne {
		log.Errorf("unable to connect to any of the provider peers for pinning operation")
		return nil
	}
```

**Comment by gmelodie** [comment]
Yup that's pretty much it, but if the list of peers all refer to the current node (meaning they're multiaddresses to the Estuary node), they will not connect because a peer cannot connect to itself, but in this case it shouldn't error out.
