### ISSUE TITLE
Levels for certain loggers are hard-coded

### ISSUE THREAD

**Issue by softwareplumber** [application-research/estuary#185]
Now that we have a config file, I feel it would be appropriate to move the default log configuration into the config file instead of main.go.

This would change behavior slightly because you'd have to run 'estuary configure' to create a config file in order to restore the 'as-is' logging behavior.

**Comment by corinne-antonia** [comment]
@whyrusleeping @alvin-reyes What do you guys think? Should we prioritize this sooner than later?
