### ISSUE TITLE
Releasing under a free software license

### ISSUE THREAD

**Issue by McSinyx** [application-research/estuary#19]
If I understand correctly, this is used to power estuary.tech in production.  It would be lovely if it is released under a [free software](https://www.gnu.org/philosophy/free-sw.en.html) license.  Personally I would suggest AGPLv3 without any CLA to best benefit the community.

**Comment by ribasushi** [comment]
@whyrusleeping @jimmylee the "common license" we copy/paste everywhere these days is https://raw.githubusercontent.com/ipfs/ipfs-repository-template/master/LICENSE.md
( [looks like this rendered](https://github.com/ipfs/ipfs-repository-template/blob/master/LICENSE.md), works/links properly on both github and pkg.go.dev )

**Comment by jimmylee** [comment]
https://github.com/application-research/estuary/blob/master/LICENSE.md
