### ISSUE TITLE
Support for API in duplicacy

### ISSUE THREAD

**Issue by RubenKelevra** [application-research/estuary#190]
Hey guys,

I've asked in the Duplicacy forum the developers for support for the estuary API, as I think if the service comes out of alpha (and allows this usage) I would really like to use it to store my backups on it.

FYI here's the tread: https://forum.duplicacy.com/t/support-for-estuary-tech-as-backend-ipfs-filecoin/6323/5

Hope you can chime in and correct me, if I stated anything wrong there. :)

Best regards!

Ruben

**Comment by corinne-antonia** [comment]
Hey @RubenKelevra, I'll take a look at the thread and let you know if estuary makes sense. Meanwhile, if you need an estuary invite, please use the official estuary invite request form. https://docs.estuary.tech/get-invite-key

**Comment by RubenKelevra** [comment]
Hey @corinne-antonia,

as long as it's not allowed to store private data and payments are ready, I'm not toooo interested tbh. I think for the data I like to share the ipfs-cluster is the better solution.

Thanks for the offer!
