### ISSUE TITLE
Investigate possible RequestFailedContentNotFound bug

### ISSUE THREAD

**Issue by gmelodie** [application-research/estuary#193]
There has been a fair amount of these error messages lately. We need to investigate.

```transfer failed: data transfer channel 12D3KooWN8vAoGd6eurUSidcpLYguQiGZwt4eVgDvbgaS7kiGTup-12D3KooWE4HCNBUkc1N6yZshnNdRRhjNA9Vy2qoJaqFF6dYNYMiS-1651703591347896279 failed to transfer data: graphsync response to peer 12D3KooWE4HCNBUkc1N6yZshnNdRRhjNA9Vy2qoJaqFF6dYNYMiS did not complete: response status code RequestFailedContentNotFound```

**Comment by brendalee** [comment]
@hannahhoward any idea what might have happened here?
