### ISSUE TITLE
Investigate possible "no announce address found for shuttle" bug

### ISSUE THREAD

**Issue by gmelodie** [application-research/estuary#194]
There was one successful storage deal made against boost a few days ago at 2022-05-06 20:59:07.722:
- Deal uuid: 7e905168-84a6-4a35-8919-10b310f3fc86
- Estuary db id: 767,499
- Client peer id: 12D3KooWCVXs8P7iq6ao4XhfAmKWrEeuKFWCJgqe9jGDMTqHYBjw
- libp2p endpoint: libp2p:///ip4/3.134.223.177/tcp/6745/p2p/12D3KooWN8vAoGd6eurUSidcpLYguQiGZwt4eVgDvbgaS7kiGTup

Today there was a deal failure with a deal from the same shuttle at 2022-05-12 11:12:41.198:
- Deal uuid: 3b430adf-3ff9-4a03-8e25-3e3d65ad5275
- Estuary db id: 768,021
- Client peer id: 12D3KooWCVXs8P7iq6ao4XhfAmKWrEeuKFWCJgqe9jGDMTqHYBjw
- Payload cid: bafybeigzrg4si6wf64lqve7wd7cn6abas36xa7nj7r2vlk5ippk5elyzsi
- Proposal cid: bafyreiexf53ibe5hisnxchlz7u35rsnp7nmnaxzy25dgel5ulna5lgaq4m
- Piece cid: baga6ea4seaqccbzj6x6yvjldq3ygklntlqtmc3q2gku4wweefqp2idn4b64bibi
- libp2p endpoint: libp2p:///ip4/3.134.223.177/tcp/6745/p2p/12D3KooWN8vAoGd6eurUSidcpLYguQiGZwt4eVgDvbgaS7kiGTup
- Error: error reading from http response stream: unexpected EOF

It looks like for some reason boost wasn't able to open a stream to the estuary shuttle.
Looking at the [estuary deal logs for the miner](https://estuary.tech/providers/errors/f0127896) it seems like the shuttle may have been started without an announce address:

```
Thursday, May 12, 2022, 8:14:13 AM 28734076 f0127896 send-proposal [lotus-1.15.2+mainnet] no announce address found for shuttle: SHUTTLE8429cbbc-2c27-4b63-850c-ca698aaf5ce7HANDLE
```

**Comment by brendalee** [comment]
@en0ma has investigated + issue is now resolved.
