### ISSUE TITLE
swag.sh script is broken with the latest release of swag (v1.8.2)

### ISSUE THREAD

**Issue by aeryz** [application-research/estuary#212]
Latest release of [swag](https://github.com/swaggo/swag/releases/tag/v1.8.2) does not contain `x86_64` version so this causes getting not found in the swag script. Even if we change it to `amd64` and successfully download it, this new version of swag starts a web server and waits for connections instead of generating the documentation and quitting.

We can stick with the version `v1.8.1`. I can open a PR for this.

**Comment by gmelodie** [comment]
I'm not sure which `swag.sh` script you're referring to, can you point me to that? Also, it seems that there is `swag_1.8.2_linux_arm64.tar.gz`, we could maybe use that?

**Comment by aeryz** [comment]
It is [scripts/swagger/swag.sh](https://github.com/application-research/estuary/blob/95bc0131c52241da4fcb3623ce742709e9ffd009/scripts/swagger/swag.sh). Apparently there is already [an issue](https://github.com/swaggo/swag/issues/1205) related to this. The darwin version is definitely broken but I don't know about the linux release. 

But anyways sticking with a version that already works might be a good idea. Because since we are fetching the latest release, our script can also fail if a broken release like this is published. We are also statically fetching `x86_64` version and for example in this release, they don't release the `x86_64` one. This also causes our script to get `Not Found` error.

**Comment by alvin-reyes** [comment]
I hard-coded this to 1.8.1. PR is now merged. https://github.com/application-research/estuary/pull/222

Note: When I wrote this script, I encountered this same issue using 1.7.x version. I had to hard code the version since swag doesn't build assets for all arch.
