### ISSUE TITLE
Upload Endpoint Returns Server Error

### ISSUE THREAD

**Issue by 3456091** [application-research/estuary#217]
I'm receiving a 500 status code for uploads larger than a couple of megabytes. For example, a 79MB upload using the following curl invocation fails this way:

```
$ curl -v -XPOST -F data=@/tmp/sjsg -H "Transfer-Encoding: chunked" -H "Authorization: Bearer $ESTUARY_TOK" https://upload.estuary.tech/content/add
```

Whereas if the payload is, say, 2.9K, it works as normal.

**Comment by hashaxis** [comment]
Same issue here, regardless of file size.

**Comment by gitannex** [comment]
Seems to be resolved now.

**Comment by alvin-reyes** [comment]
The team restarted the processes (implying that some rouge processes that is possibly misconfigured) and it now work as expected.

Discussions here: https://filecoinproject.slack.com/archives/C016APFREQK/p1653068221597879

I'll be closing this since this is now resolved.
