### ISSUE TITLE
Improve rebuilding staging bucket without blocking

### ISSUE THREAD

**Issue by en0ma** [application-research/estuary#218]
**Is your feature request related to a problem? Please describe.**

Standing an Estuary node requires rebuilding the staging buckets, this currently blocks and slows down the deployment.

**Describe the solution you'd like**

I propose to use a goroutine and a channel to build the buckets, all the while, deals will not be made until the buckets are built and the channel will notify to start accepting processing deals. 

This will greatly help speed up deployment.

**Comment by brendalee** [comment]
@en0ma @jlogelin - Jay is there any way you can look at incorporating this also?

**Comment by en0ma** [comment]
@brendalee I intend to start working on this by tomorrow
