### ISSUE TITLE
Error calling node: publishing deal: GasEstimateMessageGas error: estimating gas used: message execution failed: failed to add verified deal for client.

### ISSUE THREAD

**Issue by jimmylee** [application-research/estuary#23]
> deal bafyreibj773pvwzkyejaqtuyvcka4f4ynui7uyi36sfageweyqgdmq4454 failed: error calling node: publishing deal: GasEstimateMessageGas error: estimating gas used: message execution failed: exit 16, reason: failed to add verified deal for client: f3vnq2cmwig3qjisnx5hobxvsd4drn4f54xfxnv4tciw6vnjdsf5xipgafreprh5riwmgtcirpcdmi3urbg36a (RetCode=16)

**Comment by stuberman** [comment]
Nine deals batched up for a single publish message and they all fail, including seven Estuary deals and two DealBot deals.  74 GiB of deals. Logs show the source of the failure was Estuary.

Running a discrete markets node - m1.3.5

See verbose storage deal list and error logs from markets log attached.

[Estuary failures.txt](https://github.com/application-research/estuary/files/7004442/Estuary.failures.txt)
