### ISSUE TITLE
Remove content by CID

### ISSUE THREAD

**Issue by hkarakose** [application-research/estuary#230]
From the documentation I have come up with "[remove pin by id](https://docs.estuary.tech/pinning-remove)" service.

```
curl -X DELETE https://api.estuary.tech/pinning/pins/bafkreibcwavzcq6g4rj2x5ry2qoyki53vkektko5xkwuszcawy7k5yxmf4 -H "Content-Type: application/json" -H "Authorization: Bearer *******"
```

If I uploaded same file multiple times, the file is still accessible using CID.

Is there a service which deletes all copies of the same file by CID?

**Comment by en0ma** [comment]
Hi @hkarakose given that multiple users could own the same CID (if they uploaded the same content), it is not ideal to delete by CID. If you own both contents, then you have to make the DELETE call multiple times for each content ID

**Comment by en0ma** [comment]
closing this as no further action can be taken
