### ISSUE TITLE
Add --do-not-require-api-keys flag

### ISSUE THREAD

**Issue by gmelodie** [application-research/estuary#235]
**Is your feature request related to a problem? Please describe.**
I hate having to come up with a key every time I'm testing changes locally, we should add a way to stop requiring keys to make api calls for testing purposes.

**Describe the solution you'd like**
`./estuary --do-not-require-api-keys`

**Comment by corinne-antonia** [comment]
Hey @whyrusleeping @jlogelin, Do you guys think this makes sense?

**Comment by jlogelin** [comment]
I agree it's a bit of a hassle, but this is a convenience feature only for developers which could expose a security vulnerability on production instances. I would probably mark this one as low priority, annotated with a `proceed with caution` flag.

**Comment by anjor** [comment]
I don't think this should be worked on, and in interest of keeping things tidy I vote we close this issue. 

@jlogelin would you agree?
