### ISSUE TITLE
Staged content still remains in staging zone after it is deleted/unpinned

### ISSUE THREAD

**Issue by en0ma** [application-research/estuary#236]
When staged content is deleted (unpinned), it still remains in the staging zone and shows up in the UI

**Comment by corinne-antonia** [comment]
@en0ma Do you have everything you need to work on this?

**Comment by neelvirdy** [comment]
@en0ma i just started looking into this. is the motivation behind this that dealmaking would fail if the staging zone is attempting to aggregate a content that is unpinned? so if a user added contents, it went into a staging zone, then called DELETE /pinning/pins/:pinid on that pin, they would essentially corrupt their staging zone unless we also removed the associated content from the staging zone?

**Comment by en0ma** [comment]
> @en0ma i just started looking into this. is the motivation behind this that dealmaking would fail if the staging zone is attempting to aggregate a content that is unpinned? so if a user added contents, it went into a staging zone, then called DELETE /pinning/pins/:pinid on that pin, they would essentially corrupt their staging zone unless we also removed the associated content from the staging zone?

yes
