### ISSUE TITLE
Version endpoint

### ISSUE THREAD

**Issue by gmelodie** [application-research/estuary#251]
We should have a `/version` endpoint that returns the version an Estuary node and shuttle are running:

```
curl api.estuary.tech/version
6161975fb667302bc5ab7d18aff4528c8e241c56
```

**Comment by en0ma** [comment]
@gmelodie I do not think this is necessary, this PR https://github.com/application-research/estuary/pull/242 added support to have the app version as an HTTP header for all requests, also, it added it to the `/systems/config` endpoint. Please have a look at it.
