### ISSUE TITLE
Dedup createContent and shuttleCreateContent

### ISSUE THREAD

**Issue by gmelodie** [application-research/estuary#266]
[createContent](https://github.com/application-research/estuary/blob/53aa01e07bec710bf13ac5f01b63271c75cc874d/cmd/estuary-shuttle/main.go#L1351) and [shuttleCreateContent](https://github.com/application-research/estuary/blob/53aa01e07bec710bf13ac5f01b63271c75cc874d/cmd/estuary-shuttle/main.go#L1397) seem to do the same thing. Also, `shuttleCreateContent` uses [ShuttleCreateContentBody](https://github.com/application-research/estuary/blob/53aa01e07bec710bf13ac5f01b63271c75cc874d/util/shuttle.go#L47-L54) whereas `createContent` uses [ContentCreateBody](https://github.com/application-research/estuary/blob/53aa01e07bec710bf13ac5f01b63271c75cc874d/util/content.go#L44-L51). We should remove `shuttleCreateContent` in favor of `createContent` as well as `ShuttleCreateContentBody` in favor of `ContentCreateBody`.

**Comment by alvin-reyes** [comment]
The better approach is to inherit ContentCreateBody on the ShuttleCreateContentBody as oppose to re-writing the same attributes. This makes it better for reasons:

- unify the types for casting
- less maintenance 
- mitigates potential breaking API changes

**Comment by gmelodie** [comment]
@alvin-reyes Agreed!

**Comment by alvin-reyes** [comment]
Hi @corinne-antonia, this is already [completed](https://github.com/application-research/estuary/pull/284). We can close this github issue now.
