### ISSUE TITLE
Add Peering State() / State Endpoint

### ISSUE THREAD

**Issue by alvin-reyes** [application-research/estuary#270]
# Change
This is just a placeholder / reminder for me to use the latest go-ipfs change that exposes the peering state.

https://github.com/ipfs/go-ipfs/commit/04651e395d6e7923f592bb2c04db872e00844ad6

# Related PR/Issue/Code 

https://github.com/application-research/estuary/pull/260/files#diff-56307bdb7ded67ebe516f562b90384407b21b2d34e8b5766b42602e1fb9705f0R286

**Comment by corinne-antonia** [comment]
Hey @alvin-reyes, can I get a quick update? Can I close this?

**Comment by alvin-reyes** [comment]
No not yet. I'm waiting on my PR that exposes the state to be tagged to a release (https://github.com/ipfs/kubo/pull/9030)

Once that's done, I'll just patch estuary and add the one liner to return the state.

**Comment by alvin-reyes** [comment]
We can now close this.
