### ISSUE TITLE
Add ARM binary release build

### ISSUE THREAD

**Issue by jlogelin** [application-research/estuary#272]
Explore what it would take to add ARM binaries to the release build. There is already a baseline ARM docker image for doing the build, however there are several options for `filecoin-ffi` based on the host machine's environment. ([GPU support, etc](https://github.com/filecoin-project/filecoin-ffi#building-from-source)). Perhaps for the shrink wrapped build, it is fine to just use the vanilla libs as described in the ffi [README](https://github.com/filecoin-project/filecoin-ffi#installation-notes).

**Comment by alvin-reyes** [comment]
Not sure if this helps, I tried creating a docker image that builds the filecoin-ffi. I was thinking if we can build it and extract it, then should at least be a good workaround (without using circleci).

https://github.com/alvin-reyes/filecoin-ffi/tree/master/builder/arm64
