### ISSUE TITLE
Estuary sometime wont eat my Cars

### ISSUE THREAD

**Issue by Jorropo** [application-research/estuary#274]
**Describe the bug**

For some `.car` files, I get this output from [`linux2ipfs`](https://github.com/Jorropo/linux2ipfs):
```
1 / 3 error sending: non 200 result code: 500 / body: {"error":"encountered problem computing object references: failed to walk DAG: failed to Get CID node: merkledag: not found"}

2 / 3 error sending: non 200 result code: 500 / body: {"error":"encountered problem computing object references: failed to walk DAG: failed to Get CID node: merkledag: not found"}

3 / 3 error sending: non 200 result code: 500 / body: {"error":"encountered problem computing object references: failed to walk DAG: failed to Get CID node: merkledag: not found"}
```
Upload code:
https://github.com/Jorropo/linux2ipfs/blob/590528ab1570d5c282fc8fabcf6ab01de857e7ce/estuary.go#L47
https://github.com/Jorropo/linux2ipfs/blob/590528ab1570d5c282fc8fabcf6ab01de857e7ce/estuary.go#L65

(it works +95% of the time)

However sometimes estuary wont eat my `.car` files for some reason.

Both `go-ipfs` and `go-car` have no problem with it.

**To Reproduce**
1. First download the bad file:
   `ipfs cat bafybeihnvlakpuwtn7vyltdvpvwltbzfqpkyxbipmbvf6keo7xmzhq4icq/original.car.xz | pv -s $(ipfs --enc=json files stat /ipfs/bafybeihnvlakpuwtn7vyltdvpvwltbzfqpkyxbipmbvf6keo7xmzhq4icq/original.car.xz | jq -r .Size) | xz -dc > bad.car`
2. Try to post `bad.car` to `https://shuttle.example.com/content/add-car` (select a shuttle) (note you cannot use `barge` or an other tool that will parse the `.car`, use `curl` so it literally just send the raw bytes).

**Expected behavior**

The .car is ingested into estuary and a new deal is created.

**Actual behavior**

```
encountered problem computing object references: failed to walk DAG: failed to Get CID node: merkledag: not found
```

**Additional context**

It is possible to send this file if you lift it through go-ipfs first:
```
pv bad.car | ipfs dag import
ipfs dag export bafybeicsmoiqqjvwgra4rx6dup2m7ogqyapp54m42pleqcrh2bv4g2bzw4 > fixed.car # bafybeicsmoiqqjvwgra4rx6dup2m7ogqyapp54m42pleqcrh2bv4g2bzw4 is this precise file root
# At this point sending fixed.car to estuary works
```
This is the `bafybeihnvlakpuwtn7vyltdvpvwltbzfqpkyxbipmbvf6keo7xmzhq4icq/fixed.car.xz` file I've included (if you want to compare).

**Comment by alvin-reyes** [comment]
Would you know if this was working before? There seems to be a related PR that changed the behaviour in traversing thru the `Links()`. This could have caused the failure to retrieve the CID node.

https://github.com/application-research/estuary/pull/215/files

**Comment by Jorropo** [comment]
I am seeing this bug since I started working on linux2ipfs (~4months ago).

**Comment by Jorropo** [comment]
Update: I managed to reproduce it with Kubo.
Online mode (while the daemon is running) it works.
But with offline mode it fail just as with estuary.

**Comment by Jorropo** [comment]
For completeness, I found the bug it is a mixup between the fake root and the incremental code of linux2ipfs (my bad).

Basically in weird conditions (mtime changing but not the actually content) it would think it should reupload files it has already uploaded in a previous update.

But since it realise the hash hasn't changed, it would punch a hole in the file and seek back, zeroing that part of the `.car` and not uploading this block.
However it didn't remove it from the fake root list.

So the fake root would include a link to this block that shouldn't be. On online IPFS it would just work fine because IPFS would fetch the block from estuary when it realise it's not in the car file (since this block MUST have been uploaded in a previous upload).

The fix is here: https://github.com/Jorropo/linux2ipfs/commit/e8f899d223ad04f90e65ff82f7a569e411d18390
