### ISSUE TITLE
Improve Estuary pinning service to meet compliance

### ISSUE THREAD

**Issue by en0ma** [application-research/estuary#275]
https://www.notion.so/pl-strflt/202206-Pinning-Service-Compliance-Checker-Initial-Release-b9cdb7ddaa85401e84771fb6957f53bf

**Comment by en0ma** [comment]
@corinne-antonia I am currently working on this

**Comment by corinne-antonia** [comment]
@en0ma Ok great! Thank you

**Comment by SgtPooki** [comment]
Can I use this repo to open any future compliance check failures? w.r.t https://github.com/ipfs-shipyard/pinning-service-compliance/issues/125 ?

**Comment by alvin-reyes** [comment]
> Can I use this repo to open any future compliance check failures? w.r.t [ipfs-shipyard/pinning-service-compliance#125](https://github.com/ipfs-shipyard/pinning-service-compliance/issues/125) ?

Yes of course.
