### ISSUE TITLE
Create a DevSecOps job to gate secure coding practices

### ISSUE THREAD

**Issue by jlogelin** [application-research/estuary#295]
As a developer, I want to be able to have the CICD pipeline check that my code is secure before merging to master. There are several tools that can be used with golang to perform secure static code analysis. Probably a good initial candidate would be [gosec](https://github.com/securego/gosec)

**Comment by corinne-antonia** [comment]
Hey @jlogelin, when you are back, can you add more details here?

**Comment by jlogelin** [comment]
#296
