### ISSUE TITLE
Clarify difference between --no-storage-cron and --disable-deal-making

### ISSUE THREAD

**Issue by gmelodie** [application-research/estuary#366]
`--no-storage-cron` starts the worker that initiates new deals or reconcile old deals. If turned on no new deals and the state of existing deals will not be updated/checked.

`--disable-deal-making`: prevents making new deals but reconciliation still happens for existing deals

We need to make the differences more obvious on the `--help` strings as well as the namings of these. 

Relevant slack discussion: https://filecoinproject.slack.com/archives/C016APFREQK/p1658934465974939

**Comment by fbac** [comment]
Hi @gmelodie!

I'd like to start contributing to filecoin and estuary, can I grab this one? :)

**Comment by gmelodie** [comment]
@fbac there's already a PR in for that (https://github.com/application-research/estuary/pull/388), but you're more than welcome to review that or take another issue :)

**Comment by mvjq** [comment]
@gmelodie this issue is closed? (I'm looking for another issue to do, this one looks like a good one)

**Comment by gmelodie** [comment]
Yup closed on #388
