### ISSUE TITLE
`/add-car` don't support uploading without `Content-Length` set

### ISSUE THREAD

**Issue by Jorropo** [application-research/estuary#372]
**Describe the bug**
Trying to upload files to estuary using [linux2ipfs](https://github.com/Jorropo/linux2ipfs) it fails (where it didn't, this broke in a 1 week window arround the end of IPFS-Thing).

This is because [linux2ipfs](https://github.com/Jorropo/linux2ipfs) don't set the `Content-Length` header.

This is undocumented behavior of the API and the error message is absolutely terrible, the shuttle send a `500` with this body:
```
<html>
<head><title>500 Internal Server Error</title></head>
<body>
<center><h1>500 Internal Server Error</h1></center>
<hr><center>nginx/1.18.0 (Ubuntu)</center>
</body>
</html>
```
**To Reproduce**
Just POST a car file to `/content/add-car` to a shuttle WITHOUT `Content-Length`. (note be carefull `curl` adds `Content-Length` automagically for you by default).

**Expected behavior**
I prefer the old behaviour where the file would just be streamed until `EOF`.

**Actual behavior**
If `Content-Length` is missing it fails extremely unclearly.

**Additional context**
I understand that for some technical reason you might need `Content-Length` (like preallocating some space or whatever).
However I would like this to be documented in the HTTP API docs as well have a meaning full error message (like `Error: Content-Length required`).

---

I added a "work-around" in linux2ipfs where I just set the content length:
https://github.com/Jorropo/linux2ipfs/commit/517015a5506b4c7b429ceb4b2cbd847406c1ea12

**Comment by en0ma** [comment]
@Jorropo I verified this, I get the `EOF` error
<img width="850" alt="Screenshot 2022-07-29 at 07 08 07" src="https://user-images.githubusercontent.com/13554411/181694070-93449583-451f-4b13-982b-c8d69bf93836.png">

**Comment by en0ma** [comment]
@Jorropo I verified this, I get the `EOF` error
<img width="821" alt="Screenshot 2022-07-29 at 07 10 39" src="https://user-images.githubusercontent.com/13554411/181694265-d0d36357-1073-47e1-8ff2-1505407b17b1.png">

**Comment by Jorropo** [comment]
@en0ma your test is incorrect, I think you aren't posting the `.car` file correctly.

**Comment by Jorropo** [comment]
@en0ma try to clone https://github.com/Jorropo/estuary-push and remove the line:
```go
  req.Header.Set("Content-Length", strconv.FormatUint(uint64(stats.Size()), 10))
```
then do `go build . && ./estuary-push /tmp/example.car` you will see it fail.

**Comment by Jorropo** [comment]
It might not be after Content-Length after all. I think it's just sporadic and I got lucky.

4 is rejecting my uploads now (even with Content-Length), but 6 works.

**Comment by en0ma** [comment]
@Jorropo 4 is not completely stable at the moment, it keeps going down. Stick with 6 at the moment

**Comment by en0ma** [comment]
> @en0ma try to clone https://github.com/Jorropo/estuary-push and remove the line:
> 
> ```go
>   req.Header.Set("Content-Length", strconv.FormatUint(uint64(stats.Size()), 10))
> ```
> 
> then do `go build . && ./estuary-push /tmp/example.car` you will see it fail.

This worked for me. Even without specifying the `content-length`, it worked (and that was expected because the golang HTTP package will introspect and set it for `os.File` io.Reader)

**Comment by en0ma** [comment]
But using a tool like Postman, where I have more control and do not set it, the upload endpoint fails with `EOF`, which is expected because the body will be set to nobody. So on the Estuary end, we have to validate this before passing to the car reader.

**Comment by Jorropo** [comment]
So `EOF` is most certainly not sending the car correctly I think.
When I said until EOF, that means the car parser reads until it find no more data, not an error `EOF`.

After having a bit of tests, I think there is issues on shuttle 4 (it's now failing even with content length), I think it's just flaky and I got unlucky and saw a patterns where there was none.

**Comment by en0ma** [comment]
ok
