### ISSUE TITLE
Makeing a deal against a miner

### ISSUE THREAD

**Issue by cholcombe973** [application-research/estuary#374]
When making a deal against a specific miner with the API call `/deals/make/:miner` what is supposed to be passed in for the value of `content`? It's not clear from the code what this means. 
https://github.com/application-research/estuary/blob/9e731d743b641ea9e1fcce127c926e9a4a5631d6/handlers.go#L1550

**Comment by en0ma** [comment]
@cholcombe973 the content ID

**Comment by cholcombe973** [comment]
Ok that makes sense. May I suggest changing the variable name so it’s self
documenting?

**Comment by en0ma** [comment]
ok, will do that
