### ISSUE TITLE
NAME field no longer showing new upload file names in API response and UI

### ISSUE THREAD

**Issue by jlogelin** [application-research/estuary#382]
**Describe the bug**
When I upload files directly to shuttles, the NAME field in the user interface no longer fills in the name of the file:
ie: uploading directly to `shuttle-4` and `shuttle-6` results in the following:

**To Reproduce**

`curl
 -X POST https://shuttle-4.estuary.tech/content/add \ 
 -H "Authorization: Bearer REPLACE_ME_WITH_API_KEY" \ 
 -H "Content-Type: multipart/form-data" \ 
 -F "data=@PATH_TO_YOUR_FILE"
 `

`curl
 -X POST https://shuttle-6.estuary.tech/content/add \ 
 -H "Authorization: Bearer REPLACE_ME_WITH_API_KEY" \ 
 -H "Content-Type: multipart/form-data" \ 
 -F "data=@PATH_TO_YOUR_FILE"
 `

**Reciepts**
`https://api.estuary.tech/content/list`

```
{
        "id": 34015801,
        "updatedAt": "2022-08-03T15:10:06.836751Z",
        "cid": "bafkreih6uv6tuzih6pzqasdhronnaheuywefgixqyop3qunwm64dfj57ja",
        "name": "",
        "userId": 330,
        "description": "",
        "size": 8845,
        "type": 0,
        "active": true,
        "offloaded": false,
        "replication": 6,
        "aggregatedIn": 0,
        "aggregate": false,
        "pinning": false,
        "pinMeta": "",
        "replace": false,
        "origins": "",
        "failed": false,
        "location": "SHUTTLE791f07bc-bbba-4f69-9d3a-18c7836ab71cHANDLE",
        "dagSplit": false,
        "splitFrom": 0
    },
    {
        "id": 34015878,
        "updatedAt": "2022-08-03T15:11:46.375706Z",
        "cid": "bafkreiedwkxi2n3zv6sk745h4n7w5nkmiank4aa6idnbfrem63tyf3q5e4",
        "name": "",
        "userId": 330,
        "description": "",
        "size": 232578,
        "type": 0,
        "active": true,
        "offloaded": false,
        "replication": 6,
        "aggregatedIn": 0,
        "aggregate": false,
        "pinning": false,
        "pinMeta": "",
        "replace": false,
        "origins": "",
        "failed": false,
        "location": "SHUTTLE1d45aa63-0927-451f-85d8-748d0a8e1c39HANDLE",
        "dagSplit": false,
        "splitFrom": 0
    }
```

<img width="1556" alt="Screen Shot 2022-08-03 at 12 14 55 PM" src="https://user-images.githubusercontent.com/1556714/182646084-cfd50d13-3af8-4059-856c-0767280417bc.png">

**Comment by alvin-reyes** [comment]
reverted the code that caused this issue. This will be included on the next release.

**Comment by en0ma** [comment]
closing this, it has been resolved
