### ISSUE TITLE
Content Add through `api.estuary.tech` Fails

### ISSUE THREAD

**Issue by jlogelin** [application-research/estuary#384]
**Describe the bug**
When I try to upload content through the API, it fails with a `404 Not Found` response.

**To Reproduce**
```
curl --request POST 'https://api.estuary.tech/content/add' \
--header 'Authorization: Bearer XXXXXXX' \
--form 'data=@"anydata.png"'
```

**Expected behavior**
Content uploads without error.

**Actual behavior**
Response from API call:
```
{
    "error": {
        "code": 404,
        "reason": "Not Found",
        "details": "Not Found"
    }
}
```

**Additional context**
NA

**Comment by janzheng** [comment]
I'm trying Estuary through Swagger and also getting this problem... are there other endpoints we're supposed to use? In the docs sometimes there'll be references to `https://shuttle-4.estuary.tech/content/add` but no luck there either

**Comment by en0ma** [comment]
closing this as this has been resolved
