### ISSUE TITLE
upload.estuary.tech down?

### ISSUE THREAD

**Issue by 3456091** [application-research/estuary#395]
The upload.estuary.tech endpoint has been timing out and failing to respond to pings for a couple of days. api.estuary.tech is working fine. Is this a known problem? Has the address of the upload endpoint changed?

**Comment by alvin-reyes** [comment]
Please use api.estuary.tech for now. We'll look into upload.estuary.tech.

**Comment by 3456091** [comment]
Thanks for the update. IIRC, uploading via api.estuary.tech requires the caller to anticipate a specific error indicating the shuttle is overloaded, make a request to another endpoint to find the hostnames of the available shuttles, then try uploading to one of them. Given that upload.estuary.tech has been working for a while, is it worth me writing this extra logic, or should I just wait for it to be fixed?

**Comment by alvin-reyes** [comment]
Its better to use the shuttles to upload your content. given your logic above, use api.estuary.tech and randomly select a shuttle that's closest to you. as FYI, the shuttles are hosted on these regions.

1 - shuttle-4 US
2 - shuttle-5 APAC
3 - shuttle-6 SEA

We're cleaning up our infrastructure and the server that hosts upload.estuary.tech has already been decommissioned. The server is up but no one is maintaining it at the moment.

**Comment by alvin-reyes** [comment]
I’m going to close this now, please let me know on slack if you have any concerns.

**Comment by 3456091** [comment]
Can I just ask one last question? This is for a client-side CLI application, so upload.estuary.tech being decommissioned would have broken the binaries had I distributed them. If I'm going to hardcode other server names, I'd rather they be future-proof: should I choose a random shuttle from that list above or use the undocumented /viewer endpoint---as the rclone patches do---to find the shuttle hosts?

**Comment by janzheng** [comment]
FYI using `https://shuttle-5.estuary.tech/content/add` gives an "Internal server error" response while using api.estuary.tech gives a 404 error
