### ISSUE TITLE
Can't build `master` due to missing commit in dep

### ISSUE THREAD

**Issue by Jorropo** [application-research/estuary#399]
```console
$ export GOPROXY=direct # don't just download things from google's proxy
$ go mod download
go: github.com/ipld/go-car/v2@v2.1.2-0.20220124154420-9c7956a6eb9d: invalid version: unknown revision 9c7956a6eb9d
```
This error also shows up when doing `make build`, it's just clearer that way.

**Comment by alvin-reyes** [comment]
This is now fixed on the `dev` branch. Feel free to re-open this issue if you have concerns, alternatively you can reach out to us on our slack channel.
