### ISSUE TITLE
estuary can't be build because of undefined blockstore.ErrNotFound calls

### ISSUE THREAD

**Issue by fbac** [application-research/estuary#402]
estuary can't be built due to undefined blockstore.ErrNotFound functions called:

```bash
# github.com/application-research/estuary/util/migratebs
util/migratebs/blockstore.go:132:34: undefined: blockstore.ErrNotFound
util/migratebs/blockstore.go:147:34: undefined: blockstore.ErrNotFound
util/migratebs/blockstore.go:185:34: undefined: blockstore.ErrNotFound
```

**To Reproduce**
1. Clone the repository
2. Run "make clean all" to start the build

**Expected behavior**
estuary correctly built

**Actual behavior**
estuary build fails because of undefined functions being called

**Additional context**
blockstore changed its way to raise ErrNotFound since [this PR](https://github.com/ipfs/go-ipfs-blockstore/pull/48), which breaks compatibility. 
The logic should be changed to use ipld.ErrNotFound instead of blockstore.ErrNotFound.

**Comment by alvin-reyes** [comment]
This is now fixed on the `dev` branch. Feel free to re-open this issue if you have concerns, alternatively you can reach out to us on our slack channel.
