### ISSUE TITLE
API calling call /collections/{coluuid} returns no data when coluuid exists

### ISSUE THREAD

**Issue by snissn** [application-research/estuary#447]
**Describe the bug**
on the estuary API when i try to call /collections/{coluuid} it errors / returns nothing when it seems to exist

**To Reproduce**
1. go to https://docs.estuary.tech/swagger-ui-page#/collections/get_collections_ and fetch a list of your collections ( put in any number for user id it's ignored and i have a fix i'll make a PR for soon for that)
2. copy one of the uuids that's returned and paste it into this api call https://docs.estuary.tech/swagger-ui-page#/collections/get_collections__coluuid_ to fetch it and I am seeing an error

**Expected behavior**
return data

**Actual behavior**
no data / empty data / api throws a http error when there's no data

**Additional context**
Would love for someone to share if they are able to replicate this or not

**Comment by snissn** [comment]
figured out the root cause! 

the user id is null in the collections table! 

similar to #446 


`sqlite> select * from collections;
id|created_at|uuid|name|description|user_id|c_id
1|2022-10-01 08:57:15.213476303+00:00|92d63ade-0037-4da4-9c6b-4d902c75b0ff|test-adddir||1|
2|2022-10-01 09:03:42.22099276+00:00|b36b0474-b4af-4eb8-80bb-bf44453078f9|test-adddir||1|`

**Comment by snissn** [comment]
I think this is the relevant to investigte into https://github.com/application-research/estuary/blob/21d596246f13354751f449f37ad7da56e69caabc/handlers.go#L1114

**Comment by snissn** [comment]
been digging into this deeper. The issue isn't that data isn't getting written into the database correctly - data is going in ok. the issue is the read at the api endpoint. the client thinks that the API wants something like this

 'http://localhost:3004/collections/{coluuid}?coluuid=asdf' 

but the api actually wants something like this  

 'http://localhost:3004/collections/asdf'

**Comment by snissn** [comment]
Ok so the latest wall that this hits is that the collections refs table seems to be totally empty and this line fails to return any data and the api just returns "null":

https://github.com/application-research/estuary/blob/master/handlers.go#L3461

**Comment by snissn** [comment]
ok i figured this out! all good -- the content_add_post API had the wrong swagger doc notation before and it's fixed now

**Comment by en0ma** [comment]
> [collections/{coluuid}?coluuid=asdf](http://localhost:3004/collections/%7Bcoluuid%7D?coluuid=asdf)'

@snissn in conclusion, the issue was just the way you called the API?

**Comment by snissn** [comment]
correct yes! It had to do with the swagger documentation being out of sync with the code, then the swagger api that was generated here was wrong https://docs.estuary.tech/swagger-ui-page -- since then I've generated several PRs for fixing swagger docs/comments that should resolve this
