### ISSUE TITLE
https://api.estuary.tech/gw/ipfs throws an error on valid cid

### ISSUE THREAD

**Issue by kelindi** [application-research/estuary#452]
https://api.estuary.tech/gw/ipfs throws the following error when provided with a valid cid 
`error: ipld: could not find bafybeidlcwwae3yev6ql34up2a5xutvu76pjjwnzbrhtqsmggujng6pck4`

**To Reproduce**
1. Go to https://api.estuary.tech/gw/ipfs/bafybeidlcwwae3yev6ql34up2a5xutvu76pjjwnzbrhtqsmggujng6pck4
2. You can view the valid cid loading through the dweb gateway: https://dweb.link/ipfs/bafybeidlcwwae3yev6ql34up2a5xutvu76pjjwnzbrhtqsmggujng6pck4

**Comment by jimmylee** [comment]
Thank you @kelindi !!

**Comment by en0ma** [comment]
closing this as it has been addressed
