### ISSUE TITLE
Data Transfer Triage

### ISSUE THREAD

**Issue by jimmylee** [application-research/estuary#46]
@aarshkshah1992 is currently working on issues related to Data Transfer bugs that storage providers have complained about in the past.

**Comment by Shekelme** [comment]
> adm@lenovo92:~$ lotus-miner data-transfers list
> Sending Channels
> 
> 
> 
> Receiving Channels
> 
> ID                   Status   Receiving From  Root Cid     Initiated?  Transferred  Voucher
> 1632915003019739635  Ongoing  ...tNuNwCdE     ...1D6xDDFf  N           13.25GiB     ...pwhtq2gpg4cjcwno45joiu2b4fre5a75xa"}}
>   Message: graphsync request cancelled
> 1632915003019739637  Ongoing  ...tNuNwCdE     ...vu4cU7rH  N           9.132GiB     ...a3hlgpgedcqy5fgk5ut5f2zp2jdo6rdsqi"}}
>   Message: graphsync request cancelled
> 1632915003019739640  Ongoing  ...tNuNwCdE     ...sLThCHcE  N           8.729GiB     ...mfcdtvlhqissd5gnvmt32uwrexbduedfry"}}
>   Message: graphsync request cancelled
> 1632915003019739641  Ongoing  ...tNuNwCdE     ...EaA6PjUN  N           6.247GiB     ...7nnztcoff2o2zfae5kvohiqx7lo6hduc7y"}}
>   Message: graphsync request cancelled
> 1632915003019739644  Ongoing  ...tNuNwCdE     ...nhZmoWFF  N           4.325GiB     ...kt3iv3bfhb4dy5an62hm5ovefwoeaynsty"}}
>   Message: graphsync request cancelled
> 1632915003019739645  Ongoing  ...tNuNwCdE     ...BA83Ri7o  N           3.56GiB      ...yvi45uqstkwvibecy5jhurce532wxzguia"}}
>   Message: graphsync request cancelled
> 1632915003019739646  Ongoing  ...tNuNwCdE     ...2Pv5SzNJ  N           2.593GiB     ...jrxbnobsaocteurxlxvbbwawseq4ea2hwu"}}
>   Message: graphsync request cancelled
> 1632915003019739647  Ongoing  ...tNuNwCdE     ...CtWFieX7  N           1.576GiB     ...mpu2h2hrxpxszt4emnqgkxspionkk4qtuu"}}
>   Message: graphsync request cancelled

Cool. Recently, many transactions have been stalled during the transfer. On different miners in different locations. Finally, there is hope that the problems will be solved.

**Comment by rjan90** [comment]
Hey @aarshkshah1992! Here are the logs for the most recent storage-deals that I experienced an `Message: graphsync request cancelled`.
[Estuary-1633389281450899132-graphsync-request-cancelled.txt](https://github.com/application-research/estuary/files/7284034/Estuary-1633389281450899132-graphsync-request-cancelled.txt)

**Comment by brendalee** [comment]
@hannahhoward I think this is resolved with the lightning workstreams, right? I'm trying to do some cleanup on these issues. :)

**Comment by brendalee** [comment]
closing this issue until we see it again
