### ISSUE TITLE
Uploading to upload.estuary.tech does not work as expected

### ISSUE THREAD

**Issue by jlogelin** [application-research/estuary#462]
**Describe the bug**
When I push content up through `https://upload.estuary.tech/content/add` data does seem to be pushed up to one of the servers, as reflected by a correct ipfs.dweb.link. However the content metadata is not reflected in the user interface, or through the api (via https://api.estuary.tech/content/by-cid/<CID>)

**To Reproduce**
1. Load content via
```
curl --request POST 'https://upload.estuary.tech/content/add' \
--header 'Authorization: Bearer XXX' \
--form 'data=@"/foo/YOUR-DATA.png"'
``` 
capture the resulting CID
Note: the https://CID.ipfs.dweb.link works
2. In the web app navigate to https://estuary.tech/home and attempt to query your data, you will not find it.
3. From the command line attempt to query the content metadata with:
```
curl --request GET 'https://api.estuary.tech/content/by-cid/CID' --header 'Authorization: Bearer XXX'
```
Note the incorrect, empty resultset.

**Expected behavior**
Content should show up in both UI and via API calls

**Actual behavior**
Described above

**Additional context**
NA

**Comment by en0ma** [comment]
@jlogelin any sample CID to look at?

**Comment by jlogelin** [comment]
> @jlogelin any sample CID to look at?

`bafkreigreegsiyihdx3ugen2obrdns3jixpuobhbkz7mw4bxzlwsdm3ehi`

It is easy to reproduce, but this is the response I got back with the last test I ran:

```
{
   "cid":"bafkreigreegsiyihdx3ugen2obrdns3jixpuobhbkz7mw4bxzlwsdm3ehi",
   "retrieval_url":"https://dweb.link/ipfs/bafkreigreegsiyihdx3ugen2obrdns3jixpuobhbkz7mw4bxzlwsdm3ehi",
   "estuaryId":39989033,
   "providers":[
      "/ip4/139.178.81.141/tcp/6745/p2p/12D3KooWHe2fZ6jJJ2K2oX3EjMiXMRzvHVA5mvgYYvZvi7tEYNMe",
      "/ip4/127.0.0.1/tcp/6745/p2p/12D3KooWHe2fZ6jJJ2K2oX3EjMiXMRzvHVA5mvgYYvZvi7tEYNMe",
      "/ip4/139.178.81.141/udp/6746/quic/p2p/12D3KooWHe2fZ6jJJ2K2oX3EjMiXMRzvHVA5mvgYYvZvi7tEYNMe",
      "/ip4/127.0.0.1/udp/6746/quic/p2p/12D3KooWHe2fZ6jJJ2K2oX3EjMiXMRzvHVA5mvgYYvZvi7tEYNMe",
      "/ip4/139.178.81.141/tcp/6747/ws/p2p/12D3KooWHe2fZ6jJJ2K2oX3EjMiXMRzvHVA5mvgYYvZvi7tEYNMe",
      "/ip4/127.0.0.1/tcp/6747/ws/p2p/12D3KooWHe2fZ6jJJ2K2oX3EjMiXMRzvHVA5mvgYYvZvi7tEYNMe",
      "/ip4/100.105.51.64/tcp/6745/p2p/12D3KooWHe2fZ6jJJ2K2oX3EjMiXMRzvHVA5mvgYYvZvi7tEYNMe",
      "/ip4/10.0.0.2/tcp/6745/p2p/12D3KooWHe2fZ6jJJ2K2oX3EjMiXMRzvHVA5mvgYYvZvi7tEYNMe"
   ]
}
```

**Comment by en0ma** [comment]
@jlogelin just as I suspected;
- The file actually uploaded successfully
- the `by-cid/CID` endpoint only returns pinned (active) contents (this content has not been marked pinned yet, so wont be returned by this API call)
- The UI currently behaves like the `by-cid/CID` (verify) endpoint - it shows only active contents - that is why I proposed this change https://filecoinproject.slack.com/archives/C016APFREQK/p1665674619728969, so all contents should be shown along with their state
- finally, this content is actually pinned on the shuttle, but it probably dropped the rpc message to notify the primary to mark the state as pinned, same issue here https://filecoinproject.slack.com/archives/C016APFREQK/p1665824335920899?thread_ts=1665650121.296659&cid=C016APFREQK

I will work on a fix for this tomorrow

**Comment by en0ma** [comment]
@jlogelin can this be closed?
