### ISSUE TITLE
Estuary gateways are incorrectly handling gzip types

### ISSUE THREAD

**Issue by jlogelin** [application-research/estuary#469]
**Describe the bug**
When pulling down gzip data through `dweb.link`, it's response content type is set to `Content-Type: application/gzip`. This is correct.
When pulling down the same cid through `https://api.estuary.tech/gw/ipfs/{cid}`, the response content type is set to `Content-Type: application/x-gzip`. This is incorrect and causes issues with clients like `docker`, see:

https://github.com/moby/moby/pull/25122
https://github.com/moby/moby/issues/27642

**To Reproduce**

*Working*
1. curl -Lv 'https://bafkreibn6rsjptxv2l54irdxe7osex574ceda5wco3ijvrqkzghlzzq2eq.ipfs.dweb.link' \
  -H 'Authorization: ESTc524b2ce-ea3c-4ded-a846-3ffb5c0d376cARY' --output test.gz

Note `content-type: application/gzip`

*Broken*
1. curl -Lv 'https://api.estuary.tech/gw/ipfs/bafkreibn6rsjptxv2l54irdxe7osex574ceda5wco3ijvrqkzghlzzq2eq' \
  -H 'Authorization: ESTc524b2ce-ea3c-4ded-a846-3ffb5c0d376cARY' --output test2.gz

Note `content-type: application/x-gzip`

**Expected behavior**
Content type should be handled correctly, as it can affect third part applications. Estuary's handling of content types should be the same as `dweb.link` and return

`content-type: application/gzip`

for *.gz files.

**Actual behavior**
`content-type: application/x-gzip`

for *.gz files.

**Additional context**
Prevents [IPCR](https://github.com/application-research/ipcr) and potentially other third party applications from using optimally performant estuary gateways

**Comment by jlogelin** [comment]
Also want to call out that maybe the gateway `content-type` header value is being rewritten by nginx @alvin-reyes @en0ma

**Comment by jlogelin** [comment]
```
GET /gw/ipfs/bafkreibn6rsjptxv2l54irdxe7osex574ceda5wco3ijvrqkzghlzzq2eq HTTP/1.1
User-Agent: PostmanRuntime/7.29.0
Accept: */*
Postman-Token: 759e6c73-150d-426e-a3ab-2a8d0695bc3e
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Referer: https://api.estuary.tech/gw/ipfs/bafkreibn6rsjptxv2l54irdxe7osex574ceda5wco3ijvrqkzghlzzq2eq
Host: shuttle-6.estuary.tech
 
HTTP/1.1 200 OK
Server: nginx/1.18.0 (Ubuntu)
Date: Wed, 19 Oct 2022 14:44:26 GMT
Content-Type: application/x-gzip
Content-Length: 828088
Connection: keep-alive
Accept-Ranges: bytes
Vary: Origin
X-Appversion: v0.1.9

```

**Comment by jlogelin** [comment]
Tested on local shuttle (`shuttle-6`), noted that the x-gzip is being served from go directly:

```
~# curl -v http://127.0.0.1:3005/gw/ipfs/bafkreibn6rsjptxv2l54irdxe7osex574ceda5wco3ijvrqkzghlzzq2eq
*   Trying 127.0.0.1:3005...
* Connected to 127.0.0.1 (127.0.0.1) port 3005 (#0)
> GET /gw/ipfs/bafkreibn6rsjptxv2l54irdxe7osex574ceda5wco3ijvrqkzghlzzq2eq HTTP/1.1
> Host: 127.0.0.1:3005
> User-Agent: curl/7.81.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Accept-Ranges: bytes
< Content-Length: 828088
< Content-Type: application/x-gzip
< Vary: Origin
< X-Appversion: v0.1.9
< Date: Wed, 19 Oct 2022 15:07:48 GMT
```

**Comment by en0ma** [comment]
addressed in https://github.com/application-research/estuary/pull/478
