### ISSUE TITLE
Unable to pin if origins include /webtransport

### ISSUE THREAD

**Issue by lidel** [application-research/estuary#477]
Estuary should ignore unsupported protocols, and not fail flat like this  :pray: 

FYSA WebTransport is opt-in in Kubo 0.16, but soon will be enabled by default.

Ref. 
- https://github.com/libp2p/specs/tree/master/webtransport
- https://github.com/ipfs/kubo/blob/master/docs/changelogs/v0.16.md#-webtransport-new-experimental-transport

## How to reproduce 

1. Run Kubo 0.16 with `/webtransport` enables ([see docs](https://github.com/ipfs/kubo/blob/master/docs/changelogs/v0.16.md#-webtransport-new-experimental-transport))
2. Try to pin something to Estuary via `ipfs pin remote add --service=estuary`
3. Get  `Error: reason: "Internal Server Error", details: "failed to parse multiaddr \"/ip4/.../udp/4002/quic/webtransport/certhash/uEiD45eCWr7589blFAYwudLIwEXHzFuLC-TN0d-rC189izg/certhash/uEiDOFNSLu8nUAqeUu11cAY15whwKOJAgKCnAnGgsAVkG8g/p2p/12D3...\": unknown protocol webtransport": 500 Internal Server Error`

**Comment by en0ma** [comment]
@lidel Estuary can not tell what experimental protocols are enabled or not. You have to test and if there is no support for the protocol, please avoid using that protocol

**Comment by lidel** [comment]
I strongly disagree with shifting blame here on the user or specific IPFS implementation.

Libp2p and IPFS aim to be a robust stack. It grows over time, which means we allow people to experiment with new transports – let the most useful one flourish.  Software that is built on top of IPFS  and libp2p should not break when there is a new protocol.

Estuary should skip/ignore Multiaddrs with unknown protocols and not fail flat and deny service.

**Comment by en0ma** [comment]
Hi @lidel I better understand your ask. This has been fixed - unknown protocols are now ignored.
