### ISSUE TITLE
need to improve error messaging when wallet address has data cap

### ISSUE THREAD

**Issue by snissn** [application-research/estuary#499]
**Describe the bug**
A new user stting up their own estuary instance had a very confusing error that did not explain the solution that they needed at all

```
⇨ http server started on [::]:3004

[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1ff6824]
goroutine 1630 [running]:
main.(*ContentManager).ensureStorage(_, {_, _}, {0x2, {0x1a89d6a8, 0xedaf148b5, 0x749dfc0}, {0x1a89d6>        /home/t/estuary/replication.go:1514 +0xbc4
main.(*ContentManager).runDealWorker(0xc003a28340, {0xbf2688?, 0x3b28560?})
        /home/t/estuary/replication.go:419 +0x2ed
main.(*ContentManager).Run.func2()
        /home/t/estuary/replication.go:460 +0xa5
created by main.(*ContentManager).Run
        /home/t/estuary/replication.go:453 +0x22a
estuary.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
estuary.service: Failed with result 'exit-code'.
```

the solution that worked for them is:

```NOTE: Estuary makes only verified deals by default and this requires the wallet address to have datacap(see https://verify.glif.io/). To make deals without datacap, it will require the wallet to have FIL, and the run command will need the --verified-deal option set to false.```

we should update the error message to inform the user of this specific problem and the recommended solution (as opposed to a segfault)

**Comment by en0ma** [comment]
closing this, addressed in https://github.com/application-research/estuary/pull/503
