### ISSUE TITLE
Content add endpoints do not return correct content type header

### ISSUE THREAD

**Issue by simonwo** [application-research/estuary#540]
**Describe the bug**
The endpoints `/content/add` and `/content/add-car` don't use the correct `Content-Type` header on the HTTP response.

**To Reproduce**
1. Submit a valid file upload to the `/content/add` endpoint

Or:
1. Submit a valid CAR file to the `/content/add-car` endpoint

My request (using the API docs) looked like:
```
POST /content/add HTTP/1.1
Host: upload.estuary.tech
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:107.0) Gecko/20100101 Firefox/107.0
Accept: */*
Accept-Language: en-GB,en;q=0.5
Accept-Encoding: gzip, deflate, br
Referer: https://docs.estuary.tech/
Authorization: Bearer <...removed...>
Content-Type: multipart/form-data; boundary=---------------------------289392778424978103192602375045
Content-Length: 234
Origin: https://docs.estuary.tech
DNT: 1
Connection: keep-alive
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
```

**Expected behavior**
Response is returned with `Content-Type: application/json` header

**Actual behavior**
Response is returned with `Content-Type: text/plain` header:

```
HTTP/1.1 200 OK
Server: nginx/1.18.0 (Ubuntu)
Date: Thu, 17 Nov 2022 19:25:05 GMT
Content-Type: text/plain; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Access-Control-Allow-Origin: *
Vary: Origin
X-Appversion: v0.1.4-dirty
```

**Additional context**
This is problematic for API clients generated by `estuary-clients` because they handle the response based on the content type of the response rather than whatever the advertised content type of the API is. Hence, they are unable to read the result values of these API calls (especially the CID, which is what I need).

**Comment by en0ma** [comment]
closing this as it has been addressed

**Comment by simonwo** [comment]
Amazing, thanks!
