### ISSUE TITLE
/collections/ [GET] & /api-keys [POST] have incorrect swagger doc 

### ISSUE THREAD

**Issue by snissn** [application-research/estuary#558]
**Describe the bug**
The intention is to return an array, but we are incorrectly annotating that we are returning an array of arrays

**To Reproduce**
run this and see Nones returned https://github.com/application-research/pestuary/blob/main/examples/list-collection.py

**Expected behavior**
see correct data

{array} and [] are redundant 

-// @Success      200  {array}   []collections.Collection
+// @Success      200  {array}   collections.Collection

PR incoming

**Comment by en0ma** [comment]
done
