### ISSUE TITLE
Create /metrics endpoint

### ISSUE THREAD

**Issue by gmelodie** [application-research/estuary#571]
This requires some research since we don't quite know as of now what are the metrics people are interested in seeing.

- /public/metrics/deals-on-chain -> /metrics/deals-on/chain

**Comment by alvin-reyes** [comment]
I created separate service for metrics and it includes all the current metrics that estuary has. 

it’s here: https://metrics-api.estuary.tech/swagger/index.html

**Comment by gmelodie** [comment]
@alvin-reyes so we should not have any type of `/metrics` endpoints on estuary itself?

**Comment by alvin-reyes** [comment]
Let's put all the `/metrics` on the metrics api. These endpoints can be very expensive, we don't want it to affect the main estuary node. I have the the `deals-on-chain` already available so we can remove that.
