### ISSUE TITLE
Create /storage-providers endpoint

### ISSUE THREAD

**Issue by gmelodie** [application-research/estuary#578]
- /public/miners/storage/query/{miner}: description is weird
- remove /public/miners (goes into /miners)
- remove /public/miners/{miner}/failures (goes into miners)
- remove /public/miners/{miner}/storage/query

**Comment by jcace** [comment]
I think we should call the new one `/public/storage-providers/storage/query/{sp}` ref: https://github.com/application-research/estuary/issues/424#issuecomment-1325530906

**Comment by gmelodie** [comment]
Sure!
