### ISSUE TITLE
Estuary is sending deals smaller than 3.57GB

### ISSUE THREAD

**Issue by Aquaritek** [application-research/estuary#594]
My SP has received deals down in the KiB. Here are a couple of examples:

CreatedAt	2022-11-24 08:11:23.152 (a day ago)
Client Address	f3vnq2cmwig3qjisnx5hobxvsd4drn4f54xfxnv4tciw6vnjdsf5xipgafreprh5riwmgtcirpcdmi3urbg36a
Client Peer ID	12D3KooWCVXs8P7iq6ao4XhfAmKWrEeuKFWCJgqe9jGDMTqHYBjw
Signed Proposal CID	bafyreihd4j5se6o5t623tgfnjurzj673547uifupwt4ic6qn5izyt3kjla
Deal Data Root CID	Qmek2JPmjwdcAoc1BkJqHzDbHoHrxL5FspE5yy5y5vYzE8
Verified	Yes
Piece CID	baga6ea4seaqnpmwztv6csx2p6chn6xybqbevn2be4i3p5x5hlplx6wl5si6uefy
Piece Size	256 KiB (262,144 bytes)
Client Collateral	0 atto
Provider Collateral	69.3 nano
Storage Price / epoch / GiB	0 atto
Current Epoch	2,370,090
Start Epoch	2,386,702 (in 6 days)
End Epoch	3,881,422 (in a year)
Duration	1,494,720 (519 days)
Storage Fee	0 atto (Price per epoch x Piece Size x Duration)
Transfer Mode	Online
Transfer Type	libp2p
Transfer Size	198 KiB (203,368 bytes)
Transfer Params	
URL: libp2p:///ip4/147.75.49.99/tcp/6745/p2p/12D3KooWCVXs8P7iq6ao4XhfAmKWrEeuKFWCJgqe9jGDMTqHYBjw
Transferred	0 B (0 bytes)
Inbound File Path	/data/lotus/lotus-market/incoming/cc87b8d7-f76e-4545-8386-8bf968e57039.download
Publish Message CID	
Chain Deal ID	
Checkpoint	Complete (a day ago)
Status	Error: user manually terminated the deal

CreatedAt	2022-11-24 15:45:40.039 (a day ago)
Client Address	f3vnq2cmwig3qjisnx5hobxvsd4drn4f54xfxnv4tciw6vnjdsf5xipgafreprh5riwmgtcirpcdmi3urbg36a
Client Peer ID	12D3KooWCVXs8P7iq6ao4XhfAmKWrEeuKFWCJgqe9jGDMTqHYBjw
Signed Proposal CID	bafyreicf752sbkc5wpsuiuwlaf5wgh6b43gj4mc7fsbizmii6aqpfjd7qy
Deal Data Root CID	QmReqeDwDdEcsgkNVTsv4YTT7P6RoqaXXEVns5uWmq3yka
Verified	Yes
Piece CID	baga6ea4seaqmoiyedfzisjfesu6aebw254u2z6qyniwvkpibp3hkwa7wrcussdq
Piece Size	512 KiB (524,288 bytes)
Client Collateral	0 atto
Provider Collateral	138.7 nano
Storage Price / epoch / GiB	0 atto
Current Epoch	2,370,094
Start Epoch	2,387,611 (in 6 days)
End Epoch	3,882,331 (in a year)
Duration	1,494,720 (519 days)
Storage Fee	0 atto (Price per epoch x Piece Size x Duration)
Transfer Mode	Online
Transfer Type	libp2p
Transfer Size	365 KiB (374,105 bytes)
Transfer Params	
URL: libp2p:///ip4/147.75.49.99/tcp/6745/p2p/12D3KooWCVXs8P7iq6ao4XhfAmKWrEeuKFWCJgqe9jGDMTqHYBjw
Transferred	0 B (0 bytes)
Inbound File Path	/data/lotus/lotus-market/incoming/d99bdeed-fed1-49b1-b564-f9b089d2f0e5.download
Publish Message CID	
Chain Deal ID	
Checkpoint	Complete (a day ago)
Status	Error: user manually terminated the deal

Please see conversation that sparked ticket in slack here: 
https://filecoinproject.slack.com/archives/C016APFREQK/p1669405689269219

Tagging @anjor @jcace @jimmylee

**Comment by en0ma** [comment]
addressed
