### ISSUE TITLE
Clients need two endpoints

### ISSUE THREAD

**Issue by anjor** [application-research/estuary#642]
**Describe the bug**
Currently because api uses api.estuary.tech whereas upload uses upload.estuary.tech clients need to construct two separate endpoints in their code.

See https://github.com/filecoin-project/bacalhau/blob/9201087604398cbc1a458717cfca6f50dc22c976/pkg/publisher/estuary/endpoints.go#L19-L20

this is unnecessary overhead for our users. We should make the UX simpler by providing a single frontdoor.

@simonwo for awareness.

**Comment by en0ma** [comment]
> **Describe the bug** Currently because api uses api.estuary.tech whereas upload uses upload.estuary.tech clients need to construct two separate endpoints in their code.
> 
> See https://github.com/filecoin-project/bacalhau/blob/9201087604398cbc1a458717cfca6f50dc22c976/pkg/publisher/estuary/endpoints.go#L19-L20
> 
> this is unnecessary overhead for our users. We should make the UX simpler by providing a single frontdoor.
> 
> @simonwo for awareness.

upload via https://api.estuary.tech has historically been problematic but was finally fixed properly using a proxied request in the last release. So I think the [code](https://github.com/filecoin-project/bacalhau/blob/9201087604398cbc1a458717cfca6f50dc22c976/pkg/publisher/estuary/endpoints.go#L19-L20) can be updated to use `https://api.estuary.tech` only.

**Comment by simonwo** [comment]
> upload via https://api.estuary.tech has historically been problematic but was finally fixed properly using a proxied request in the last release. So I think the [code](https://github.com/filecoin-project/bacalhau/blob/9201087604398cbc1a458717cfca6f50dc22c976/pkg/publisher/estuary/endpoints.go#L19-L20) can be updated to use `https://api.estuary.tech` only.

Ah, it's true! 

This also means #567 is less of an issue for me because the `api.estuary.tech` endpoints do return the correct content type. Thanks all!

**Comment by en0ma** [comment]
> > upload via https://api.estuary.tech has historically been problematic but was finally fixed properly using a proxied request in the last release. So I think the [code](https://github.com/filecoin-project/bacalhau/blob/9201087604398cbc1a458717cfca6f50dc22c976/pkg/publisher/estuary/endpoints.go#L19-L20) can be updated to use `https://api.estuary.tech` only.
> 
> Ah, it's true!
> 
> This also means #567 is less of an issue for me because the `api.estuary.tech` endpoints do return the correct content type. Thanks all!

Yeah, I fixed it here https://github.com/application-research/estuary/pull/562. I will try to do the same for `uploads.estuary.tech`

**Comment by en0ma** [comment]
@anjor can this be closed?

**Comment by anjor** [comment]
Yup if @simonwo is happy with it.

**Comment by simonwo** [comment]
Yep it's working fine on our side now!

**Comment by en0ma** [comment]
Thanks @simonwo
