### ISSUE TITLE
Provider Deal List -> All deals have "invalid date"

### ISSUE THREAD

**Issue by jcace** [application-research/estuary#647]
**Describe the bug**
The "Created Date" column in the SP Deals list always says **Invalid Date**

**To Reproduce**
Navigate to the **Storage Provider -> Deals** page.

Examples:
https://estuary.tech/providers/deals/f0706693
https://estuary.tech/providers/deals/f01886797

**Expected behavior**
Date column should be populated

**Actual behavior**
Date column always says "Invalid Date"

**Additional context**
The Deal Errors page appears to have the correct Created Date field
ex) https://estuary.tech/providers/errors/f01886797

**Comment by en0ma** [comment]
addressed
