### ISSUE TITLE
Implement an intelligent load-balancer to redirect client requests to shuttles

### ISSUE THREAD

**Issue by sheriflouis-FF** [application-research/estuary#65]
Today clients connect to https://api.estuary.tech to add data, get data and interact with the various API endpoints Estuary exposes.
There is no automated mechanism to steer clients away when a shuttle node goes down or its local storage fills up. Implementing a loadbalancer with a new URL (https://upload.estuary.tech) will solve many problems related to outages and maintenance windows. 

Quoting cake: "we could really use is some notion of 'load' across the different estuary nodes, so we can use that to do smarter load balancing. Load balancing right now is done manually by editing priority in the database because we don't have any automated metrics to do switching back and forth."

**Comment by brendalee** [comment]
@en0ma have we done anything related to this/is this the approach that we should take?

**Comment by en0ma** [comment]
@brendalee I think this might have been resolved with the shuttle-proxy at `https://upload.estuary.tech/` - though, I do not know much about how it decides which shuttle to use, but `https://upload.estuary.tech/` totally abstracts the decision away from the users and handles when shuttles are down. So I think this has been addressed.
