### ISSUE TITLE
add support for ARM

### ISSUE THREAD

**Issue by sheriflouis-FF** [application-research/estuary#71]
When I try to compile estuary under an ARM machine I get:
`# github.com/filecoin-project/filecoin-ffi/generated
/usr/bin/ld: skipping incompatible extern/filecoin-ffi/generated/../libfilcrypto.a when searching for -lfilcrypto
/usr/bin/ld: skipping incompatible extern/filecoin-ffi/generated/../libfilcrypto.a when searching for -lfilcrypto
/usr/bin/ld: skipping incompatible extern/filecoin-ffi/generated/../libfilcrypto.a when searching for -lfilcrypto
/usr/bin/ld: skipping incompatible extern/filecoin-ffi/generated/../libfilcrypto.a when searching for -lfilcrypto
/usr/bin/ld: skipping incompatible extern/filecoin-ffi/generated/../libfilcrypto.a when searching for -lfilcrypto
/usr/bin/ld: cannot find -lfilcrypto
collect2: error: ld returned 1 exit status
make: *** [Makefile:67: estuary] Error 2
`

Architecture:
`# lscpu
Architecture:                    aarch64
CPU op-mode(s):                  32-bit, 64-bit
`
OS:
`
5.4.0-1045-aws
`

**Comment by alvin-reyes** [comment]
Quick investigation on this It seems its there is a workaround based on this lotus issue here https://github.com/filecoin-project/lotus/issues/1779#issuecomment-629932097 

```
RUSTFLAGS="-C target-cpu=native -g" FFI_BUILD_FROM_SOURCE=1 make clean deps bench
```

**Comment by en0ma** [comment]
@sheriflouis-FF closing this for now, if the solution proposed by @alvin-reyes did not help, please let us know.
