### ISSUE TITLE
Retrieval commands don't work in the verify webUI

### ISSUE THREAD

**Issue by sheriflouis-FF** [application-research/estuary#76]
If i try to retrieve a CID using the retrieval command returned by the CID verify webUI fails with:

`$ lotus client retrieve --miner f01392893 bafybeierkfdggz26tvbflaxrzgrlzb6k3g2ptv7hbkpskzxhoqtali2gtu data-2755366
ERROR: The received offer errored: retrieval query offer was unavailable:`

The lotus client retrieve command includes the CID of the file, while the correct way of retrieving a CID is to determine the rootCID of the CID I am trying to retrieve. 

The steps that work as follows: 
Determine the label of the dealID:
`$ lotus state get-deal 2755366
{
  "Proposal": {
    "PieceCID": {
      "/": "baga6ea4seaqawzo77rc75wrt7elirecptorakkv3txjhrmrkkxabvj6za2urogi"
    },
    "PieceSize": 2147483648,
    "VerifiedDeal": true,
    "Client": "f0397376",
    "Provider": "f01392893",
    "Label": "QmR6dciuJGeR5LzSuyn9nUu8pn6qPP9FTdaeeF2mWDzSi3",
    "StartEpoch": 1306869,
    "EndEpoch": 2801589,
    "StoragePricePerEpoch": "0",
    "ProviderCollateral": "330814207684018",
    "ClientCollateral": "0"
  },
  "State": {
    "SectorStartEpoch": 1287571,
    "LastUpdatedEpoch": -1,
    "SlashEpoch": -1
  }
}
`
use the CID in Label field: QmR6dciuJGeR5LzSuyn9nUu8pn6qPP9FTdaeeF2mWDzSi3
`lotus client retrieve --miner f01392893 QmR6dciuJGeR5LzSuyn9nUu8pn6qPP9FTdaeeF2mWDzSi3 QmR6dciuJGeR5LzSuyn9nUu8pn6qPP9FTdaeeF2mWDzSi3`
The problem with that approach I could end up downloading a whole DAG if I only need a single CID. 
To overcome this I have to add a path selector, which means I have to know where my CID is with the DAG beforehand.
`lotus client retrieve --miner f01392893 --datamodel-path-selector 'Links/0/Hash'  QmR6dciuJGeR5LzSuyn9nUu8pn6qPP9FTdaeeF2mWDzSi3 file.png
`

**Comment by marshall** [comment]
This will also require a PR to estuary-www, so I filed application-research/estuary-www#17
