### ISSUE TITLE
Unable to Login to Estuary.tech

### ISSUE THREAD

**Issue by jlogelin** [application-research/estuary#771]
**Describe the bug**
Unable to log in to estuary.tech

`console.log`:

![image](https://user-images.githubusercontent.com/1556714/207472728-9c999242-5058-4dbe-97c2-420fcaff59f0.png)

**To Reproduce**
1. Try to log in.

**Expected behavior**
Logging in.

**Actual behavior**
Doesn't log in

**Additional context**
I really wish I could log in.

**Comment by snissn** [comment]
CORs issue - did we change something with headers? something with a proxy we have?

**Comment by jlogelin** [comment]
`content/add` returning 

```
{
    "error": {
        "code": 500,
        "reason": "Internal Server Error",
        "details": "failed to request createContent: <html>\r\n<head><title>503 Service Temporarily Unavailable</title></head>\r\n<body>\r\n<center><h1>503 Service Temporarily Unavailable</h1></center>\r\n<hr><center>nginx/1.18.0 (Ubuntu)</center>\r\n</body>\r\n</html>\r\n"
    }
}
```

**Comment by jlogelin** [comment]
@alvin-reyes is the 👑
