### ISSUE TITLE
bug: bsget Compile error!

### ISSUE THREAD

**Issue by mmikey1** [application-research/estuary#82]
When I run 'make clean all', it shows the following error

go build  -o bsget ./cmd/bsget
# github.com/application-research/estuary/cmd/bsget
cmd/bsget/main.go:54:23: cannot use ctx (type context.Context) as type config.Option in argument to libp2p.New
Makefile:87: recipe for target 'bsget' failed
make: *** [bsget] Error 2

how to fix it? Thank you!

**Comment by aronchick** [comment]
This has been fixed in the most recent build. Please update your local download. Thanks!

**Comment by marshall** [comment]
closing since this has been addresssed
