### ISSUE TITLE
GET /collections/{col-uuid} Excruciatingly Slow

### ISSUE THREAD

**Issue by pythonicode** [application-research/estuary#822]
**Describe the bug**
Hi there, when I'm running queries to get contents of a specific path of a collection in the Estuary DB, I get highly varied and extremely slow response times ranging from 1 to 15 seconds.

**To Reproduce**

```js
        const url = dir ? `https://api.estuary.tech/collections/${col_id}?dir=${dir}`
                        : `https://api.estuary.tech/collections/${col_id}`;
        const start = Date.now();
        const result = await fetch(url, {
            method: 'GET',
            headers: {
                "Authorization": "Bearer " + process.env.ESTUARY_API_KEY,
            }
        });
        const data = await result.json();
        const end = Date.now();
        console.log(`GET ${url} took ${end - start}ms`);
```

```
GET https://api.estuary.tech/collections/5bf508d7-34c0-4ef7-8853-6dda75be491c?dir=/ took 853ms
GET https://api.estuary.tech/collections/5bf508d7-34c0-4ef7-8853-6dda75be491c?dir=/ took 1395ms
GET https://api.estuary.tech/collections/5bf508d7-34c0-4ef7-8853-6dda75be491c?dir=/ took 8364ms
GET https://api.estuary.tech/collections/5bf508d7-34c0-4ef7-8853-6dda75be491c?dir=/ took 3951ms
GET https://api.estuary.tech/collections/5bf508d7-34c0-4ef7-8853-6dda75be491c?dir=/ took 13101ms
```

**Additional context**

I see that in the following file there is a TODO which seems to imply that there is an unoptimized query being run to fetch the content of the collection in [handlers.go](https://github.com/application-research/estuary/blob/3e0a3d3ccd0e5742d012f099c9e1ba2f0bb01503/api/v1/handlers.go#L3316-L3324)

```go
	// TODO: optimize this a good deal
	var refs []util.ContentWithPath
	if err := s.DB.Model(collections.CollectionRef{}).
		Where("collection = ?", col.ID).
		Joins("left join contents on contents.id = collection_refs.content").
		Select("contents.*, collection_refs.path as path").
		Scan(&refs).Error; err != nil {
		return err
	}
```

I was wondering if it was as simple as improving the query or if the underlying models need to be changed to make this lookup more efficient? I don't know enough about Estuary's underlying system to try to fix this but if anyone has some insight that would be amazing.

Thanks.

**Comment by pythonicode** [comment]
I also see some potentially useful functions in  [collections.go](https://github.com/application-research/estuary/blob/3e0a3d3ccd0e5742d012f099c9e1ba2f0bb01503/collections/collections.go#L71-L120).

It seems like the endpoint is doing a lot of duplicate work? I tried optimizing it here: #823

**Comment by pythonicode** [comment]
Happy New Year! @en0ma @gmelodie 

Wondering if I could get some eyes on this because it's really slowing down production in my app. Thanks.

**Comment by gmelodie** [comment]
Hello there! I'm sorry for the delay here. Thank you for flagging this to us! Question: did you experience slowness only on this specific endpoint? Are other collection endpoints slow too? What about endpoints unrelated to collections? Are those slow too? I'm trying to see if there's an issue in the code optimization or if it's infra related.

**Comment by pythonicode** [comment]
> Hello there! I'm sorry for the delay here. Thank you for flagging this to us! Question: did you experience slowness only on this specific endpoint? Are other collection endpoints slow too? What about endpoints unrelated to collections? Are those slow too? I'm trying to see if there's an issue in the code optimization or if it's infra related.

Hey, this endpoint was the only one that was noticeably slow. I'm creating a collection without much issue: takes only a handful of milliseconds, but the content endpoint was taking 10+ seconds on occasion as I said (which is extreme).

**Comment by pythonicode** [comment]
Endpoint seems to run faster. Associated PR is still open at #823, I think there are still some valid code optimization in there, but for now the content endpoint seems to be working just fine.
