### ISSUE TITLE
How can we delete/unpin a file?

### ISSUE THREAD

**Issue by AllanOricil** [application-research/estuary#84]
I read the docs and did not find any DELETE request. Will deletion be supported? I saw that in filecoin we can unpin files and this is kind of a deletion mechanism. I would like to be able to remove files when needed. 
Also, if my deal is for 180 days, what will happen to my file after this period? Will it get purged? How can I tell the provider I want to keep it longer? How can the provider tell me that the deal is about to expire?

**Comment by sheriflouis-FF** [comment]
Hi Allan,
The unpinning happens on the IPFS blockstore level, use the unpinning API to do that. Note that If files have made it to a Filecoin provider it will not be deleted until the deal expires. Estuary makes deals up to their maximum period of 540 days. Before the expiration, Estuary makes new deals for the files, so we will indefinitely renew the deals.

**Comment by brendalee** [comment]
@AllanOricil Let us know if you have any more questions.
