### ISSUE TITLE
Consolidate metrics by method

### ISSUE THREAD

**Issue by lanzafame** [application-research/estuary#97]
i.e. `estuary_blks_base_sync_total` -> `estuary_blks_base_total{method="sync|delete|deletemany|get|has|etc......."}`
why? So that queries over all calls are also possible, i.e. `sum(rate(estuary_blks_base_total{}[1m])) by (method)`

**Comment by brendalee** [comment]
@alvin-reyes could this be incorporated into the metrics/dashboard work you're doing?

**Comment by brendalee** [comment]
@alvin-reyes FYI as you're working on the metrics/dashboard, could you sync with @lanzafame on this input? :)

**Comment by corinne-antonia** [comment]
Hey @alvin-reyes, any updates on this?

**Comment by alvin-reyes** [comment]
Grafana dashboard is now available
